In [2]:
import numpy as np
import pandas as pd
import matplotlib

In [32]:
df = pd.read_csv("../data/Fish.csv")
df.head()

   Category Species  Weight   Height   Width  Length1  Length2  Length3
0         1   Bream   242.0  11.5200  4.0200     23.2     25.4     30.0
1         1   Bream   290.0  12.4800  4.3056     24.0     26.3     31.2
2         1   Bream   340.0  12.3778  4.6961     23.9     26.5     31.1
3         1   Bream   363.0  12.7300  4.4555     26.3     29.0     33.5
4         1   Bream   430.0  12.4440  5.1340     26.5     29.0     34.0

In [33]:
species_map = {
    "Bream": "Tilapia",
    "Roach": "Tilapia",
    "Perch": "Nile Perch",
    "Pike": "Nile Perch",
    "Smelt": "Trout",
    "Parkki": "Catfish",
    "Whitefish": "Trout"
}

df["Species"] = df["Species"].map(species_map)

In [34]:
df

     Category  Species  Weight   Height   Width  Length1  Length2  Length3
0           1  Tilapia   242.0  11.5200  4.0200     23.2     25.4     30.0
1           1  Tilapia   290.0  12.4800  4.3056     24.0     26.3     31.2
2           1  Tilapia   340.0  12.3778  4.6961     23.9     26.5     31.1
3           1  Tilapia   363.0  12.7300  4.4555     26.3     29.0     33.5
4           1  Tilapia   430.0  12.4440  5.1340     26.5     29.0     34.0
..        ...      ...     ...      ...     ...      ...      ...      ...
154         6    Trout    12.2   2.0904  1.3936     11.5     12.2     13.4
155         6    Trout    13.4   2.4300  1.2690     11.7     12.4     13.5
156         6    Trout    12.2   2.2770  1.2558     12.1     13.0     13.8
157         6    Trout    19.7   2.8728  2.0672     13.2     14.3     15.2
158         6    Trout    19.9   2.9322  1.8792     13.8     15.0     16.2

[159 rows x 8 columns]

In [35]:
import numpy as np

def generate_species_environment():
    return {
        "Tilapia": {
            "temperature": np.random.normal(27, 2),
            "oxygen": np.random.normal(6, 1),
            "ph": np.random.uniform(6.5, 9),
            "density": np.random.randint(10, 40),
            "feeding_rate": np.random.uniform(2, 5)
        },
        "Nile Perch": {
            "temperature": np.random.normal(28, 1.5),
            "oxygen": np.random.normal(6, 0.8),
            "ph": np.random.uniform(6.5, 8.5),
            "density": np.random.randint(5, 20),
            "feeding_rate": np.random.uniform(3, 6)
        },
        "Catfish": {
            "temperature": np.random.normal(29, 2),
            "oxygen": np.random.normal(4, 1),
            "ph": np.random.uniform(6, 8),
            "density": np.random.randint(20, 60),
            "feeding_rate": np.random.uniform(3, 8)
        },
        "Trout": {
            "temperature": np.random.normal(15, 3),
            "oxygen": np.random.normal(9, 1),
            "ph": np.random.uniform(6.5, 8),
            "density": np.random.randint(5, 25),
            "feeding_rate": np.random.uniform(1, 4)
        }
    }

In [39]:
species_env = generate_species_environment()

def assign_env(row):
    return pd.Series(species_env[row["Species"]])

In [40]:
env_df = df.apply(assign_env, axis=1)

df = pd.concat([df, env_df], axis=1)

In [41]:
df

,Category,Species,Weight,Height,Width,Length1,Length2,Length3,temperature,oxygen,ph,density,feeding_rate
0,1,Tilapia,242.0,11.5200,4.0200,23.2,25.4,30.0,23.537487,6.391877,8.382254,17.0,3.386294
1,1,Tilapia,290.0,12.4800,4.3056,24.0,26.3,31.2,23.537487,6.391877,8.382254,17.0,3.386294
2,1,Tilapia,340.0,12.3778,4.6961,23.9,26.5,31.1,23.537487,6.391877,8.382254,17.0,3.386294
3,1,Tilapia,363.0,12.7300,4.4555,26.3,29.0,33.5,23.537487,6.391877,8.382254,17.0,3.386294
4,1,Tilapia,430.0,12.4440,5.1340,26.5,29.0,34.0,23.537487,6.391877,8.382254,17.0,3.386294
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,6,Trout,12.2,2.0904,1.3936,11.5,12.2,13.4,11.758396,7.733541,7.291402,6.0,1.914678
155,6,Trout,13.4,2.4300,1.2690,11.7,12.4,13.5,11.758396,7.733541,7.291402,6.0,1.914678
156,6,Trout,12.2,2.2770,1.2558,12.1,13.0,13.8,11.758396,7.733541,7.291402,6.0,1.914678
157,6,Trout,19.7,2.8728,2.0672,13.2,14.3,15.2,11.758396,7.733541,7.291402,6.0,1.914678
158,6,Trout,19.9,2.9322,1.8792,13.8,15.0,16.2,11.758396,7.733541,7.291402,6.0,1.914678

In [42]:
cols_to_remove = ["Weight", "Height", "Width", "Length1", "Length2", "Length3"]

df = df.drop(columns=[col for col in cols_to_remove if col in df.columns])

In [43]:
df

     Category  Species  temperature    oxygen        ph  density  feeding_rate
0           1  Tilapia    23.537487  6.391877  8.382254     17.0      3.386294
1           1  Tilapia    23.537487  6.391877  8.382254     17.0      3.386294
2           1  Tilapia    23.537487  6.391877  8.382254     17.0      3.386294
3           1  Tilapia    23.537487  6.391877  8.382254     17.0      3.386294
4           1  Tilapia    23.537487  6.391877  8.382254     17.0      3.386294
..        ...      ...          ...       ...       ...      ...           ...
154         6    Trout    11.758396  7.733541  7.291402      6.0      1.914678
155         6    Trout    11.758396  7.733541  7.291402      6.0      1.914678
156         6    Trout    11.758396  7.733541  7.291402      6.0      1.914678
157         6    Trout    11.758396  7.733541  7.291402      6.0      1.914678
158         6    Trout    11.758396  7.733541  7.291402      6.0      1.914678

[159 rows x 7 columns]

In [44]:
def generate_initial_weight(species):
    if species == "Tilapia":
        return np.random.uniform(5, 100)
    elif species == "Catfish":
        return np.random.uniform(10, 200)
    elif species == "Trout":
        return np.random.uniform(2, 80)
    elif species == "Nile Perch":
        return np.random.uniform(10, 150)

In [46]:
df["initial_weight"] = df["Species"].apply(generate_initial_weight)

df

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377
...,...,...,...,...,...,...,...,...
154,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,14.665990
155,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,29.883142
156,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,13.565146
157,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,30.287603
158,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,17.889450

In [47]:
df["days"] = np.random.randint(7, 120, size=len(df))
df

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight,days
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730,20
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222,101
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352,12
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477,17
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377,15
...,...,...,...,...,...,...,...,...,...
154,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,14.665990,26
155,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,29.883142,103
156,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,13.565146,61
157,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,30.287603,99
158,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,17.889450,117

In [53]:
def compute_growth(row):
    # Base growth rate per species
    if row["Species"] == "Tilapia":
        base_rate = 0.015
    elif row["Species"] == "Catfish":
        base_rate = 0.02
    elif row["Species"] == "Trout":
        base_rate = 0.012
    elif row["Species"] == "Nile Perch":
        base_rate = 0.018

    # Environmental influence
    temp_factor = row["temperature"] / 28
    oxygen_factor = row["oxygen"] / 6

    growth_factor = temp_factor * oxygen_factor

    # Final growth
    return row["initial_weight"] * (
        1 + base_rate * row["days"] * growth_factor
    )

In [54]:
df["target_weight"] = df.apply(compute_growth, axis=1)
df

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight,days,target_weight
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730,20,32.287015
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222,101,114.341760
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352,12,83.967586
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477,17,89.718749
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377,15,71.677971
...,...,...,...,...,...,...,...,...,...,...
154,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,14.665990,26,17.142745
155,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,29.883142,103,49.875403
156,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,13.565146,61,18.939828
157,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,30.287603,99,49.763548
158,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,17.889450,117,31.484516

In [55]:
df["target_weight"] += np.random.normal(0, 5, len(df))
df

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight,days,target_weight
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730,20,38.463446
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222,101,122.072389
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352,12,87.312856
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477,17,87.797827
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377,15,69.737151
...,...,...,...,...,...,...,...,...,...,...
154,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,14.665990,26,17.100791
155,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,29.883142,103,57.946006
156,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,13.565146,61,14.789391
157,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,30.287603,99,43.157702
158,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,17.889450,117,30.158320

In [56]:
df["target_weight"] = df["target_weight"].clip(lower=df["initial_weight"])
df

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight,days,target_weight
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730,20,38.463446
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222,101,122.072389
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352,12,87.312856
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477,17,87.797827
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377,15,69.737151
...,...,...,...,...,...,...,...,...,...,...
154,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,14.665990,26,17.100791
155,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,29.883142,103,57.946006
156,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,13.565146,61,14.789391
157,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,30.287603,99,43.157702
158,6,Trout,11.758396,7.733541,7.291402,6.0,1.914678,17.889450,117,30.158320

In [58]:
df.to_csv("../data/fish_growth_prediction.csv", index=False)

In [60]:
df = pd.read_csv("../data/fish_growth_prediction.csv")
df.head()

,Category,Species,temperature,oxygen,ph,density,feeding_rate,initial_weight,days,target_weight
0,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,25.449730,20,38.463446
1,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,48.517222,101,122.072389
2,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,72.311352,12,87.312856
3,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,73.039477,17,87.797827
4,1,Tilapia,23.537487,6.391877,8.382254,17.0,3.386294,59.657377,15,69.737151